/******************************
** File: Buildscript_1.00.027.sql
** Name: Buildscript_1.00.027
** Auth: McNiel Viray
** Date: 06 July 2017
**************************
** Change History
**************************
** Modify sp [dbo].[wfmpcp_GetStaffPlanner_sp] and [dbo].[wfmpcp_GetAssumptionsHeadcount_sp]

*******************************/
USE WFMPCP
GO

PRINT N'Altering [dbo].[wfmpcp_GetAssumptionsHeadcount_sp]...';


GO
ALTER PROCEDURE [dbo].[wfmpcp_GetAssumptionsHeadcount_sp]
	@lobid AS NVARCHAR(MAX)='',
	@start AS NVARCHAR(MAX)='',
	@end AS NVARCHAR(MAX)='',	
	@includeDatapoint BIT = 1,
	@tablename AS NVARCHAR(MAX)='WeeklyAHDatapoint',
	@segmentcategoryid  AS NVARCHAR(MAX)='',
	@segmentid  AS NVARCHAR(MAX)=''
AS
BEGIN
	DECLARE @cols AS NVARCHAR(MAX)
		,@query  AS NVARCHAR(MAX)
		,@select  AS NVARCHAR(MAX)
		,@whereClause AS NVARCHAR(MAX) = ' '
		,@orderBy AS NVARCHAR(MAX)

	IF(@start <> '' AND @end <> '')
	BEGIN
		SELECT @cols = STUFF((SELECT ',' + QUOTENAME([Date]) 
							FROM WeeklyAHDatapoint
							WHERE [Date] BETWEEN CAST(@start AS DATE) AND CAST(@end AS DATE)
							GROUP BY [Date]
							ORDER BY [Date]
					FOR XML PATH(''), TYPE
					).value('.', 'NVARCHAR(MAX)') 
				,1,1,'')

		UPDATE WeeklyAHDatapoint
			SET [Data]=
			CASE DatapointID 
				WHEN 1 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 2 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 3 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) 
				WHEN 4 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 5 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 6 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
				WHEN 7 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
				WHEN 8 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
				WHEN 9 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 10 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 11 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 12 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + '%'
				WHEN 13 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
				WHEN 14 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 15 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 16 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 17 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 18 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 19 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 20 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 21 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 22 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 23 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 24 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 25 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 26 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 27 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 28 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 29 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 30 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 31 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 32 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 33 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 34 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 35 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 36 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 37 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 38 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 39 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 40 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 41 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 42 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 43 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 44 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 45 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 46 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 47 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 48 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 49 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 50 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 51 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 52 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 53 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 54 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 55 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 56 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 57 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 58 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 59 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 60 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 61 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 62 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 63 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 64 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 65 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 66 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 67 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 68 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 69 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 70 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 71 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 72 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 73 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 74 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 75 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 76 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 77 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 78 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 79 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 80 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 81 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 82 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 83 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 84 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 85 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 86 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 87 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 91 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 92 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 93 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 94 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 95 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 96 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 97 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 98 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 99 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 100 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 101 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 102 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 103 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 104 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 105 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 106 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 107 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 108 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 109 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 110 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 111 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 112 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 113 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 114 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 115 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 116 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 117 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				ELSE [Data]	END
			WHERE Lobid=CAST(@lobid AS BIGINT)
			AND [Date] BETWEEN CAST(@start AS DATE) AND CAST(@end AS DATE)
	END
	ELSE
	BEGIN
		SELECT @cols = STUFF((SELECT ',' + QUOTENAME([Date]) 
							FROM WeeklyAHDatapoint
							WHERE [Date] BETWEEN DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) AND DATEADD(MONTH,12,GETDATE())
							GROUP BY [Date]
							ORDER BY [Date]
					FOR XML PATH(''), TYPE
					).value('.', 'NVARCHAR(MAX)') 
				,1,1,'')

		UPDATE WeeklyAHDatapoint
			SET [Data]=
			CASE DatapointID 
				WHEN 1 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 2 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 3 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) 
				WHEN 4 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 5 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 6 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
				WHEN 7 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
				WHEN 8 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
				WHEN 9 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 10 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 11 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 12 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + '%'
				WHEN 13 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
				WHEN 14 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 15 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 16 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 17 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 18 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 19 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 20 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 21 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 22 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 23 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 24 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 25 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 26 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 27 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 28 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 29 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 30 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 31 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 32 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 33 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 34 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 35 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 36 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 37 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 38 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 39 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 40 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 41 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 42 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 43 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 44 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 45 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 46 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 47 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 48 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 49 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 50 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 51 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 52 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 53 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 54 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 55 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 56 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 57 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 58 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 59 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 60 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 61 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
				WHEN 62 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 63 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 64 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 65 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 66 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 67 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 68 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 69 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 70 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 71 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 72 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 73 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 74 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 75 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 76 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 77 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 78 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 79 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 80 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 81 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 82 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 83 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 84 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 85 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 86 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 87 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 91 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 92 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 93 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 94 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 95 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 96 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 97 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 98 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 99 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 100 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 101 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 102 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 103 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 104 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 105 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
				WHEN 106 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 107 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 108 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 109 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 110 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 111 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 112 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 113 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 114 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 115 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 116 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				WHEN 117 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
				ELSE [Data]	END
			WHERE Lobid=CAST(@lobid AS BIGINT)
			AND [Date] BETWEEN DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) AND DATEADD(MONTH,12,GETDATE())
	END
		
	IF(@includeDatapoint=1)
	BEGIN
		SET @select = '
				SELECT s.ID SegmentID, d.ID DatapointID, s.Name Segment, d.Name [Datapoint],' + @cols + '
				FROM (
					SELECT *
					FROM
					(
						SELECT LobID,datapointid,[Date],Data from ' + @tablename + 
					' ) x		
					PIVOT
					(
						MAX(Data)
						FOR [Date] IN ('+ @cols +')
					)p
				) A
				INNER JOIN Datapoint d ON d.ID=A.DatapointID
				INNER JOIN Segment s ON s.ID=d.SegmentID
				INNER JOIN SegmentCategory sc ON sc.ID=s.SegmentCategoryID
				WHERE 1=1 '
	END
	ELSE
	BEGIN
		SET @select = '
				SELECT ' + @cols + '
				FROM (
					SELECT *
					FROM
					(
						SELECT LobID,datapointid,[Date],Data from ' + @tablename + 
					' ) x		
					PIVOT
					(
						MAX(Data)
						FOR [Date] IN ('+ @cols +')
					)p
				) A
				INNER JOIN Datapoint d ON d.ID=A.DatapointID
				INNER JOIN Segment s ON s.ID=d.SegmentID
				INNER JOIN SegmentCategory sc ON sc.ID=s.SegmentCategoryID
				WHERE 1=1 '
	END

	IF(@segmentcategoryid != '')
	BEGIN
		SET @whereClause = @whereClause + ' AND s.SegmentCategoryID=' + @segmentcategoryid
	END

	IF(@segmentid != '')
	BEGIN
		SET @whereClause = @whereClause + ' AND s.ID=' + @segmentid
	END

	IF(@lobid != '')
	BEGIN
		SET @whereClause = @whereClause + ' AND a.LoBID=' + @lobid
	END	

	SET @orderBy = ' ORDER BY sc.SortOrder,s.SortOrder,d.SortOrder'
	SET @query = @select + @whereClause + @orderBy

	EXECUTE(@query);
END
GO
PRINT N'Altering [dbo].[wfmpcp_GetStaffPlanner_sp]...';


GO
ALTER PROCEDURE [dbo].[wfmpcp_GetStaffPlanner_sp]
	@lobid AS NVARCHAR(MAX)='',
	@start AS NVARCHAR(MAX)='',
	@end AS NVARCHAR(MAX)='',	
	@includeDatapoint BIT = 1,
	@segmentid  AS NVARCHAR(MAX)=''
AS
BEGIN
	DECLARE @cols AS NVARCHAR(MAX)
		,@query  AS NVARCHAR(MAX)
		,@select  AS NVARCHAR(MAX)
		,@whereClause AS NVARCHAR(MAX) = ' '
		,@orderBy AS NVARCHAR(MAX)

	IF(@start <> '' AND @end <> '')
	BEGIN
		SELECT @cols = STUFF((SELECT ',' + QUOTENAME([Date]) 
							FROM WeeklyStaffDatapoint
							WHERE [Date] BETWEEN CAST(@start AS DATE) AND CAST(@end AS DATE)
							GROUP BY [Date]
							ORDER BY [Date]
					FOR XML PATH(''), TYPE
					).value('.', 'NVARCHAR(MAX)') 
				,1,1,'')


		UPDATE WeeklyStaffDatapoint
		SET [Data]=
				CASE DatapointID 
					WHEN 1 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 2 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 3 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 4 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 5 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
					WHEN 6 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
					WHEN 7 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 8 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 9 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 10 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 11 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 12 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 13 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) 
					WHEN 14 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) 
					WHEN 15 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 16 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 17 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
					WHEN 18 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
					WHEN 19 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
					WHEN 20 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
					WHEN 21 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
					WHEN 22 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
					ELSE CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(10)) END
		--FROM WeeklyStaffDatapoint 
		WHERE Lobid=CAST(@lobid AS BIGINT)
			AND [Date] BETWEEN CAST(@start AS DATE) AND CAST(@end AS DATE)
	END
	ELSE
	BEGIN
		SELECT @cols = STUFF((SELECT ',' + QUOTENAME([Date]) 
							FROM WeeklyStaffDatapoint
							WHERE [Date] BETWEEN DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) AND DATEADD(MONTH,12,GETDATE())
							GROUP BY [Date]
							ORDER BY [Date]
					FOR XML PATH(''), TYPE
					).value('.', 'NVARCHAR(MAX)') 
				,1,1,'')


		UPDATE WeeklyStaffDatapoint
		SET [Data]=
				CASE DatapointID 
					WHEN 1 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 2 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 3 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 4 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 5 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
					WHEN 6 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
					WHEN 7 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 8 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 9 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 10 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 11 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 12 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX))
					WHEN 13 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) 
					WHEN 14 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) 
					WHEN 15 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 16 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX))
					WHEN 17 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
					WHEN 18 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
					WHEN 19 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
					WHEN 20 THEN CAST(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0) AS NVARCHAR(MAX)) + ' %'
					WHEN 21 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
					WHEN 22 THEN CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(MAX)) 
					ELSE CAST(CEILING(ROUND(CAST(LTRIM(RTRIM(REPLACE(Data,'%',''))) AS DECIMAL(10,2)),0)) AS NVARCHAR(10)) END
		--FROM WeeklyStaffDatapoint 
		WHERE Lobid=CAST(@lobid AS BIGINT)
			AND [Date] BETWEEN DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) AND DATEADD(MONTH,12,GETDATE())
	END
		
	IF(@includeDatapoint=1)
	BEGIN
		SET @select = '
				SELECT s.ID SegmentID, d.ID DatapointID, s.Name Segment, d.Name [Datapoint],' + @cols + '
				FROM (
					SELECT *
					FROM
					(
						SELECT LobID,datapointid,[Date],[Data] from WeeklyStaffDatapoint
					 ) x		
					PIVOT
					(
						MAX(Data)
						FOR [Date] IN ('+ @cols +')
					)p
				) A
				INNER JOIN StaffDatapoint d ON d.ID=A.DatapointID
				INNER JOIN StaffSegment s ON s.ID=d.SegmentID
				WHERE 1=1 '
	END
	ELSE
	BEGIN
		SET @select = '
				SELECT ' + @cols + '
				FROM (
					SELECT *
					FROM
					(
						SELECT LobID,datapointid,[Date],[Data] from WeeklyStaffDatapoint
					) x		
					PIVOT
					(
						MAX(Data)
						FOR [Date] IN ('+ @cols +')
					)p
				) A
				INNER JOIN StaffDatapoint d ON d.ID=A.DatapointID
				INNER JOIN StaffSegment s ON s.ID=d.SegmentID
				WHERE 1=1 '
	END
	
	IF(@segmentid != '')
	BEGIN
		SET @whereClause = @whereClause + ' AND s.ID=' + @segmentid
	END

	IF(@lobid != '')
	BEGIN
		SET @whereClause = @whereClause + ' AND a.LoBID=' + @lobid
	END	

	SET @orderBy = ' ORDER BY s.SortOrder,d.SortOrder'
	SET @query = @select + @whereClause + @orderBy

	EXECUTE(@query);
END
GO
PRINT N'Update complete.';


GO
