CREATE TABLE [dbo].[AuditTrail]
(
	[ID] BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT [PK_AuditTrail_ID] PRIMARY KEY([ID]), 
    [AuditEntry] NVARCHAR(MAX) NOT NULL, 
	[CreatedBy] NVARCHAR(40) NOT NULL,
    [DateCreated] DATETIME NOT NULL DEFAULT GETDATE(), 
    [DateModified] DATETIME NULL DEFAULT NULL
)
