CREATE TABLE CSVRawData
(
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() CONSTRAINT [pk_CSVRawData_ID] PRIMARY KEY([ID]),
	SiteID BIGINT,
	CampaignID BIGINT,
	LoBID BIGINT,
	[Filename] NVARCHAR(15),
	RowNumber BIGINT,
	ColumnNumber BIGINT,
	[Data] NVARCHAR(150) NOT NULL DEFAULT('0'),
	CreatedBy NVARCHAR(150),
	DateCreated DATETIME NOT NULL  DEFAULT GETDATE(),
	Active BIT NOT NULL DEFAULT(1)
)
