CREATE TABLE [dbo].[Module]
(
	[ID] BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT[PK_Module_ID] PRIMARY KEY([ID]), 	
	[ParentID] BIGINT NOT NULL CONSTRAINT[DF_Module_ParentID] DEFAULT(0),
    [Name] NVARCHAR(50) NOT NULL, 
	[FontAwesome] NVARCHAR(100) NULL,
	[MenuIcon] NVARCHAR(100) NULL,
    [Route] NVARCHAR(MAX) NOT NULL, 
	[SortOrder] INT NOT NULL DEFAULT 0,
	[CreatedBy] NVARCHAR(250) NULL,
	[ModifiedBy] NVARCHAR(250) NULL,
    [DateCreated] DATETIME NOT NULL CONSTRAINT[DF_Module_DateCreated] DEFAULT GETDATE(), 
    [DateModified] DATETIME NULL,
	[Active] BIT NOT NULL CONSTRAINT[DF_Module_Active] DEFAULT(1)
)
